### PR TITLE
Added support for PLAIN/SCRAM SASL

### PR DESCRIPTION
**Pull request by roche-d**
Simple patch to support PLAIN/SCRAM authentication

### CODE REVIEW

**Comment by repeatedly** [comment]
Thanks for the patch!
But the copy & paste is hard to maintain.
How about this client setup routine into here?

https://github.com/fluent/fluent-plugin-kafka/blob/master/lib/fluent/plugin/kafka_plugin_util.rb#L35

- in module

```
def setup_kafka_client
   # patch code here
end
```

- in plugin code

```
@kafka = setup_kafka_client
```

**Comment by tomiloza** [comment]
Can we merge this into master, we would really need this!

**Comment by repeatedly** [comment]
@roche-d How about my comment?

**Comment by repeatedly** [comment]
No reply. We need refactoring in the future but merged.

**Pull request merged**
