### PR TITLE
Preliminary support for sasl/gssapi authentication in ruby-kafka. 

### PR DESCRIPTION
**Pull request by tmeinlschmidt**
see #115 .

### CODE REVIEW

**Comment by repeatedly** [comment]
Waiting new ruby-kafka which supports SASL/GSSAPI

**Comment by tmeinlschmidt** [comment]
@repeatedly yep. have to do some changes in ruby-kafka PR, and then do the same here, but I think it should work :)

**Comment by LesTR** [comment]
Hi, what's status of this PR please?

**Comment by repeatedly** [comment]
Need ruby-kafka supports SASL.
See https://github.com/zendesk/ruby-kafka/issues/119

**Comment by ringhiera** [comment]
It would be interesting to have a bit more detail about this feature of kafka plugin, in particular how to use it to authenticate fluent when pushing to kafka.
Is there any documentation available?

**Comment by LesTR** [comment]
@repeatedly https://github.com/zendesk/ruby-kafka/issues/119 was closed and released in v0.4.0. Is here any other blocker or it can be merged too?

**Comment by repeatedly** [comment]
I will release new version in this weekend.

**Comment by LesTR** [comment]
Thanks!

**Comment by repeatedly** [comment]
Thanks. I will release new version after check ruby-kafka v0.4 changes.

**Comment by repeatedly** [comment]
Released v0.6.0.

**Pull request merged**
