### PR TITLE
Make Kafka password a secret

### PR DESCRIPTION
**Pull request by danmx**
It stops the leak of Kafka password in logs

### CODE REVIEW

**Comment by cosmo0920** [comment]
You can re-send your commit with `git commit -s --amend && git push -f origin secret_password`
Please try these commands. :)

**Comment by danmx** [comment]
Thx, I've noticed it now 😜

**Comment by cosmo0920** [comment]
Hmm, You can rebase off master with `git rebase master` and push forcely.
Then, only your commit should be shown in this PR.

**Comment by repeatedly** [comment]
DCO passed. Thanks!

**Pull request merged**
