### PR TITLE
Add support for avro output type

### LINKED ISSUE #114: output_data_type avro support
I want to use fluentd output to Kafka in Avro, can Avro be supported?, according to Avro document, Avro provide:
```
Rich data structures.
A compact, fast, binary data format.
A container file, to store persistent data.
Remote procedure call (RPC).
Simple integration with dynamic languages. Code generation is not required to read or write data files nor to use or implement RPC protocols. Code generation as an optional optimization, only worth implementing for statically typed languages.
```

### PR DESCRIPTION
**Pull request by woostundy**
let kafka_buffered support avro output type. 
Fixes #114

### CODE REVIEW

**Comment by repeatedly** [comment]
I'm not sure why this is needed.
If fluent-plugin-avro has the problem, fixing it is better.
Duplicated code is not good.

**Comment by cosmo0920** [comment]
> If you want use avro-plugin and kafka-plugin together, you have to change the code.

What is the change that we have to do?

**Comment by woostundy** [comment]
> What is the change that we have to do?
I'm so sorry for reply late, and I find it's not necessary.
avro plugin and kafka plugin work well together. 
I'm sorry for that I didn't read the code carefully but just thought it coun't work since others said they failed.

**Comment by woostundy** [comment]
> What is the change that we have to do?

I'm so sorry for reply late, and I find it's not necessary.
avro plugin and kafka plugin work well together.
I'm sorry for that I didn't read the code carefully but just thought it coun't work since others said they failed.

**Comment by jose5918** [comment]
@woostundy Would you be willing to provide some guidance on how you got them working together? I'm also using the kafka_buffered and wanted to try the avro plugin

**Comment by jose5918** [comment]
Nvm I figured out the usage. Didn't realize you could sub in a formatter as an output data type
```
    output_data_type "avro"
    <formatter>
      @type avro
    </formatter>
    schema_json {"type":"record","name":"example","namespace":"org.example","fields":[{"name":"message","type":"string"}]}```

**Comment by woostundy** [comment]
> @woostundy Would you be willing to provide some guidance on how you got them working together? I'm also using the kafka_buffered and wanted to try the avro plugin

I'm sorry for reply so later. You can try config like that
```
    output_data_type "avro"
    <formatter>
      @type avro
      schema_json {"type":"record","name":"example","namespace":"org.example","fields":[{"name":"message","type":"string"}]}
    </formatter>
```

**Comment by Zephery** [comment]
I try this, but it turns out "error_class=Fluent::ConfigError error="schema_json or schema_file (but not both) is required"", anyone can help?
```xml
<match **>
  @type kafka_buffered

  brokers xxx

  flush_interval 3s

  default_topic xxx

  output_data_type avro
  compression_codec gzip

  <formatter>
    @type avro
    schema_json {"type":"record","name":"example","namespace":"org.example","fields":[{"name":"message","type":"string"}]}
  </formatter>
</match>
```
image

**Comment by cosmo0920** [comment]
This can be achieved with `<formatter>` directive and `output_data_type` parameter.
Closing.

**Pull request closed without merging**
