### PR TITLE
in_kafka_group: send heartbeat if necessary

### PR DESCRIPTION
**Pull request by GiedriusS**
We've spotted that processing a batch of Kafka messages in fluentd
sometimes takes a long time and because of that Kafka consumer groups go
into a constant rebalancing state. Fluentd lacks observability to understand
what plugin is taking a long time so adding this as a stop gap solution
for the moment. It's not trivial to add duration histograms to Fluentd
so this is a stop-gap solution for now.

Kudos to @marijus-ravickas for the idea. More details available at
https://www.marionzualo.com/2019/08/10/always-manually-send-heartbeats-when-processing-message-batches-in-ruby-kafka/.

Tests still pass:

```
37 tests, 42 assertions, 0 failures, 0 errors, 0 pendings, 7 omissions, 0 notifications         
100% passed
```

### CODE REVIEW

**Review by niaurys — APPROVED** [review]

**Review by cosmo0920 — APPROVED** [review]
I like this idea. Seems reasonable. :+1:

**Comment by raytung** [comment]
Looking at `ruby-kafka` source code https://github.com/zendesk/ruby-kafka/blob/292f2d5a5b8ef4572485617121bf61a6725414cf/lib/kafka/consumer.rb#L359, it looks like they are already triggering heartbeat after every batch. 

From what you've described, I would be interested to look into your `session.timeout.ms` (https://kafka.apache.org/documentation/#consumerconfigs_session.timeout.ms, should default to 45s in Kafka 3.0.0, and can be set via the `session_timeout` parameter), and see if it makes sense to bump that.

**Comment by cosmo0920** [comment]
So, should we decline this PR and add descriptions for processing high volume log?

**Comment by raytung** [comment]
@cosmo0920 I think so. If the author finds a need for this again, they can re-open the PR in a future date

**Comment by cosmo0920** [comment]
OK. Let's close this PR then.

**Pull request closed without merging**
