### PR TITLE
adds ssl client cert key password

### PR DESCRIPTION
**Pull request by raytung**
Hey team and happy new year!

This PR fixes https://github.com/fluent/fluent-plugin-kafka/issues/459 and also properly marks `ssl_client_cert_key_password` as secret in `out_rdkafka2` as I just happen to stumble upon it.

### CODE REVIEW

**Review by ashie — APPROVED** [review]
LGTM
Thanks!

**Review by ashie — CHANGES_REQUESTED** [review]
Oops, I overlooked that there is a remaining thing.
We need to follow the change in #481.

**Comment by raytung** [comment]
@ashie I've rebased `master` thanks

**Comment by ashie** [comment]
Thanks!
I'll create a new pull request to fix indentation & etc around this code.

**Pull request merged**
