### PR TITLE
 Adding support to not use SSL when using SASL on "in" plugin...

### PR DESCRIPTION
**Pull request by mcarbonneaux**
like "out" plugin commit 8ea31d00d4d8ba0598171e7f6dbb4be9e05724b2, this pull request add support to not use SSL when using SASL to "in" plugin....

### CODE REVIEW

**Comment by repeatedly** [comment]
Thanks!

**Comment by abernardino** [comment]
Are there plans to support this on the "out" plugin as well?

**Comment by repeatedly** [comment]
> Are there plans to support this on the "out" plugin as well?

See PR description. out plugins support this parameter...

**Comment by repeatedly** [comment]
> Why is it not honored for the PLAIN or other mechanism? Any plan to support that?

Because first patch covers only SASL SCRAM.
Patches for adding more mechanizm are welcome.

**Comment by doublening** [comment]
Thanks. Is there document for building fluent-plugin-kafka gem locally?

**Comment by mcarbonneaux** [comment]
Honoring plain text sasl over non crypted layer is risky... 

Scram can be done... 

I think is why the original author have not done for plain text...

**Pull request merged**
